# memory capacity (KB)
memory_capacity_glb: 128
memory_capacity_mtile: 0.5

# element size (byte)
element_size: 2

# tool configuration
tiling_algorithm: "btree"
qtree_tile_merging: False
performance_model: "opal"

# tiling overhead
# unit: per nnz process time
# ex: tile_overhead = 5 means:
# to setup a tile, it takes the same
# amount of time processing 5 nnzs
tile_overhead: 5

# operation
operation: "elementwise-mul"

# input matrix name
input_matrix_names:
  - "A"
  - "B"
  