# memory capacity (KB)
memory_capacity_glb: 128
memory_capacity_mtile: 4

# tool configuration
tiling_algorithm: "qtree"
qtree_tile_merging: True
performance_model: "opal"

# operation
operation: "elementwise-add"

# input matrix name
input_matrix_names:
  - "A"
  - "B"
  